export const NAME = 'products';

export const GET_LIST_PRODUCTS_SAGA_STARTED =
  '[products]/GET_LIST_PRODUCTS_SAGA_STARTED';
export const GET_LIST_PRODUCTS_SAGA_FINISHED =
  '[products]/GET_LIST_PRODUCTS_SAGA_FINISHED';
export const GET_LIST_PRODUCTS_SAGA_ERROR =
  '[products]/GET_LIST_PRODUCTS_SAGA_ERROR';
